export enum ErrorCodeEnum {
  NoContentCanBeModified = 1000,

  PostNotFound = 10000,
  PostExist = 10001,
  CategoryNotFound = 10002,
  CategoryCannotDeleted = 10003,
  CategoryAlreadyExists = 10004,

  UserNotFound = 30000,
  UserExist = 30001,

  LabNotFound = 40000,
  BiomarkerNotFound = 40010,
  IcdNotFound = 40020,
  CptNotFound = 40030,
  LoincNotFound = 40040,
  TestNotFound = 41000,
  TestVersionNotFound = 41010,
  TestConfigurationNotFound = 41020,
  OrderFormSectionNotFound = 41100,
  OrderFormTemplateNotFound = 41110,
  LabOrderNotFound = 42000,
  PatientNotFound = 42010,
  ProviderNotFound = 42020,
  OrganizationNotFound = 42030,
  OrganizationEndpointNotFound = 42040,
}

export const ErrorCode = Object.freeze<Record<ErrorCodeEnum, [string, string, number]>>({
  [ErrorCodeEnum.NoContentCanBeModified]: ['no content can be modified', '没有内容可以被修改', 400],
  [ErrorCodeEnum.PostNotFound]: ['post not found', '文章不存在', 404],
  [ErrorCodeEnum.PostExist]: ['post already exist', '文章已存在', 400],
  [ErrorCodeEnum.CategoryNotFound]: ['category not found', '分类不存在', 404],
  [ErrorCodeEnum.CategoryCannotDeleted]: [
    'there are other posts in this category, cannot be deleted',
    '该分类中有其他文章，无法被删除',
    400,
  ],
  [ErrorCodeEnum.CategoryAlreadyExists]: ['category already exists', '分类已存在', 400],
  [ErrorCodeEnum.UserNotFound]: ['user not found', '用户不存在', 404],
  [ErrorCodeEnum.UserExist]: ['user already exist', '用户已存在', 400],
  [ErrorCodeEnum.LabNotFound]: ['lab not found', '实验室不存在', 404],
  [ErrorCodeEnum.BiomarkerNotFound]: ['biomarker not found', '生物标记物不存在', 404],
  [ErrorCodeEnum.IcdNotFound]: ['icd not found', 'ICD 不存在', 404],
  [ErrorCodeEnum.CptNotFound]: ['cpt not found', 'CPT 不存在', 404],
  [ErrorCodeEnum.LoincNotFound]: ['loinc not found', 'LOINC 不存在', 404],
  [ErrorCodeEnum.TestNotFound]: ['test not found', '检测不存在', 404],
  [ErrorCodeEnum.TestVersionNotFound]: ['test version not found', '检测版本不存在', 404],
  [ErrorCodeEnum.TestConfigurationNotFound]: ['test configuration not found', '配置不存在', 404],
  [ErrorCodeEnum.OrderFormSectionNotFound]: ['order form section not found', '表单分区不存在', 404],
  [ErrorCodeEnum.OrderFormTemplateNotFound]: [
    'order form template not found',
    '表单模板不存在',
    404,
  ],
  [ErrorCodeEnum.LabOrderNotFound]: ['lab order not found', '检测订单不存在', 404],
  [ErrorCodeEnum.PatientNotFound]: ['patient not found', '患者不存在', 404],
  [ErrorCodeEnum.ProviderNotFound]: ['provider not found', '医生不存在', 404],
  [ErrorCodeEnum.OrganizationNotFound]: ['organization not found', '机构不存在', 404],
  [ErrorCodeEnum.OrganizationEndpointNotFound]: [
    'organization endpoint not found',
    '机构接口不存在',
    404,
  ],
})
