-- Create enum type and alter LabOrderStatus.status to use it

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'LabOrderStatusEnum') THEN
    CREATE TYPE "LabOrderStatusEnum" AS ENUM (
      'DRAFT',
      'SUBMITTED',
      'PENDING_REVIEW',
      'PRIOR_AUTH_PENDING',
      'PRIOR_AUTH_APPROVED',
      'SPECIMEN_SHIPPED',
      'SPECIMEN_IN_TRANSIT',
      'SPECIMEN_RECEIVED',
      'ACCESSIONING_IN_PROGRESS',
      'ACCESSIONING_CANCELLED',
      'ACCESSIONING_FAILED',
      'ACCESSIONING_PENDING',
      'ACCESSIONING_PENDING_REVIEW',
      'ACCESSIONING_PENDING_APPROVAL',
      'ACCESSIONING_PENDING_REJECTION',
      'ACCESSIONING_PENDING_CANCELLATION',
      'ACCESSIONING_COMPLETED',
      'CANCELLED',
      'WET_LAB_COMPLETED',
      'DRY_LAB_COMPLETED',
      'ANALYSIS_IN_PROGRESS',
      'ANALYSIS_COMPLETED',
      'ANALYSIS_FAILED',
      'ANALYSIS_PENDING',
      'ANALYSIS_PENDING_REVIEW',
      'ANALYSIS_PENDING_APPROVAL',
      'ANALYSIS_PENDING_REJECTION',
      'ANALYSIS_PENDING_CANCELLATION',
      'RESULTED',
      'REJECTED',
      'RESULTS_DELIVERED',
      'RESULTS_DELIVERED_TO_PATIENT',
      'RESULTS_DELIVERED_TO_PROVIDER',
      'RESULTS_DELIVERED_TO_INSTITUTION',
      'RESULTS_DELIVERED_TO_PAYOR',
      'RESULTS_DELIVERED_TO_PAYOR_REJECTED',
      'RESULTS_DELIVERED_TO_PAYOR_APPROVED',
      'CPT_CODES_UPDATED',
      'ICD_CODES_UPDATED',
      'DOCTOR_NOTES_UPDATED',
      'CLINICAL_NOTES_UPDATED',
      'MEDICAL_NECESSITY_VERIFIED'
    );
  END IF;
END $$;

ALTER TABLE "LabOrderStatus"
  ALTER COLUMN status TYPE "LabOrderStatusEnum" USING (status::"LabOrderStatusEnum");

